name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pharo
        uses: hpi-swa/setup-pharo@v1
        with:
          version: 12.0

      - name: Load project
        run: |
          pharo Pharo.image eval "
          Metacello new
            baseline: 'MatrixProject';
            repository: 'filetree://.';
            load."

      - name: Run Tests
        run: |
          pharo Pharo.image eval "
          (TestSuite new
            addAllTestCasesFromCategory: 'MatrixProject-Tests';
            run) asString."

