name: CI

on:
  push:
    branches:
      - 'main'  
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pharo
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: Pharo64-12.0  

      - name: Run Tests
        run: smalltalkci -s Pharo64-12.0
        shell: bash
        timeout-minutes: 15

